ALTER TABLE picture ADD COLUMN width SMALLINT UNSIGNED DEFAULT NULL;
ALTER TABLE picture ADD COLUMN height SMALLINT UNSIGNED DEFAULT NULL;
# Update earlier pictures to current width/height
ALTER TABLE picture MODIFY width SMALLINT UNSIGNED NOT NULL;
ALTER TABLE picture MODIFY height SMALLINT UNSIGNED NOT NULL;
