ALTER TABLE account ADD COLUMN email VARCHAR(255) DEFAULT NULL;
ALTER TABLE account ADD COLUMN email_verified_time INT UNSIGNED DEFAULT NULL;
ALTER TABLE account ADD COLUMN timezone TINYINT SIGNED DEFAULT NULL;
