CREATE TABLE waitlist_event (
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	account_id BIGINT UNSIGNED NOT NULL,
	user_agent VARCHAR(1024) DEFAULT NULL,
	FOREIGN KEY (account_id) REFERENCES account(id),
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
