CREATE TABLE addressLookup (
	type TINYINT UNSIGNED NOT NULL,
	address VARCHAR(255) NOT NULL,
	personId BIGINT UNSIGNED DEFAULT NULL,
	name VARCHAR(255) NOT NULL,
	conversationIdsJson VARCHAR(1024) DEFAULT NULL,
	createdTime INT UNSIGNED NOT NULL,
	claimedTime INT UNSIGNED DEFAULT NULL,
	PRIMARY KEY (type, address)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE addressVerification (
	id BIGINT UNSIGNED NOT NULL,
	token VARCHAR(36) NOT NULL,
	address VARCHAR(255) NOT NULL,
	addressType TINYINT UNSIGNED NOT NULL,
	name VARCHAR(255) NOT NULL,
	color TINYINT UNSIGNED NOT NULL,
	passwordHash VARCHAR(60) NOT NULL,
	createdTime INT UNSIGNED NOT NULL,
	usedTime INT UNSIGNED DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
