CREATE TABLE person (
	-- personal info
	personId BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	locale CHAR(5) DEFAULT NULL,
	name VARCHAR(255) DEFAULT NULL,
	birthdate DATE DEFAULT NULL,
	gender ENUM('male','female') DEFAULT NULL,
	-- addresses
	facebookId BIGINT UNSIGNED DEFAULT NULL,
	phoneNumbersJson VARCHAR(1024) DEFAULT NULL,
	emailAddressesJson VARCHAR(1024) DEFAULT NULL,
	-- utility data
	passwordHash VARCHAR(255) NOT NULL,
	lastClientUidBlockStart BIGINT UNSIGNED NOT NULL DEFAULT 0,
	lastClientUidBlockEnd BIGINT UNSIGNED NOT NULL DEFAULT 100000,
	pushJson VARCHAR(1024) DEFAULT NULL,
	-- times
	joinedTime INT UNSIGNED NOT NULL,
	disabledTime INT UNSIGNED DEFAULT NULL,
	PRIMARY KEY (personId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE participation (
	participationId BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	personId BIGINT UNSIGNED NOT NULL,
	conversationId BIGINT UNSIGNED DEFAULT NULL,
	lastMessageTime INT UNSIGNED DEFAULT NULL,
	lastReceivedTime INT UNSIGNED DEFAULT NULL,
	lastReadTime INT UNSIGNED DEFAULT NULL,
	peopleJson VARCHAR(2048) NOT NULL,
	recentJson VARCHAR(2048) DEFAULT NULL,
	picturesJson VARCHAR(2048) DEFAULT NULL,
	PRIMARY KEY (participationId),
	UNIQUE KEY keyPersonIdConversationId (personId, conversationId),
	FOREIGN KEY keyPersonId (personId) REFERENCES person(personId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
